import { StyleSheet } from 'react-native';
export const colors = {
  ink: '#172C35',
  muted: '#65777B',
  primary: '#007E73',
  pale: '#E3F3EE',
  bg: '#F4F7F6',
  white: '#FFFFFF',
  border: '#DBE5E2',
  danger: '#B64735',
  warn: '#98620F',
};
export const ui = StyleSheet.create({
  flex: { flex: 1 },
  page: { flex: 1, backgroundColor: colors.bg },
  content: { padding: 20, paddingBottom: 32, gap: 16 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  title: {
    fontSize: 27,
    fontWeight: '800',
    color: colors.ink,
    letterSpacing: -0.7,
  },
  heading: { fontSize: 18, fontWeight: '700', color: colors.ink },
  text: { fontSize: 14, color: colors.ink, lineHeight: 21 },
  muted: { fontSize: 13, color: colors.muted, lineHeight: 20 },
  eyebrow: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.primary,
    letterSpacing: 1.3,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    gap: 12,
  },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: colors.ink,
  },
  button: {
    minHeight: 48,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
  },
  buttonText: { fontSize: 15, fontWeight: '700', color: colors.white },
  chip: {
    minHeight: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  chipSelected: { backgroundColor: colors.pale, borderColor: colors.primary },
  small: { fontSize: 12, color: colors.muted },
  separator: { height: 1, backgroundColor: colors.border },
});
