name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Secret Status
        run: echo "키 값이 등록되어 있는지 확인 (true면 정상) -> ${{ secrets.SSH_KEY != '' }}"

      - name: git pull and docker compose up
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ${{ secrets.APP_DIR }}
            git pull origin main
            docker compose up -d --build